openapi: 3.2.0
info:
  title: Agent Handler Subpackage Credentials API
  version: 1.0.0
servers:
- url: https://ah-api.merge.dev
tags:
- name: subpackage_credentials
paths:
  /api/v1/credentials/registered-users/{registered_user_id}/connectors/{connector_slug}/:
    delete:
      operationId: registered-users-connectors-destroy
      summary: Delete credentials
      description: Deletes credentials for a Registered User's Connector
      tags:
      - subpackage_credentials
      parameters:
      - name: connector_slug
        in: path
        description: The slug of the Connector
        required: true
        schema:
          type: string
      - name: registered_user_id
        in: path
        description: Agent Handler ID of the Registered User
        required: true
        schema:
          type: string
          format: uuid
      - name: Authorization
        in: header
        description: Token-based authentication with required prefix "Bearer"
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful response
components:
  securitySchemes:
    tokenAuth:
      type: http
      scheme: bearer
      description: Token-based authentication with required prefix "Bearer"
