openapi: 3.2.0
info:
  title: HRIS Subpackage Timesheet Entries API
  version: 1.0.0
servers:
- url: https://api.merge.dev/api
- url: https://api-eu.merge.dev/api
- url: https://api-ap.merge.dev/api
tags:
- name: subpackage_timesheetEntries
paths:
  /hris/v1/timesheet-entries:
    get:
      operationId: list
      summary: List
      description: Returns a list of `TimesheetEntry` objects.{/* BEGIN_HRIS_TIMESHEETENTRY_FETCH_SUPPORTED_FIELDS */}{/* END_HRIS_TIMESHEETENTRY_FETCH_SUPPORTED_FIELDS */}
      tags:
      - subpackage_timesheetEntries
      parameters:
      - name: created_after
        in: query
        description: If provided, will only return objects created after this datetime.
        required: false
        schema:
          type: string
          format: date-time
      - name: created_before
        in: query
        description: If provided, will only return objects created before this datetime.
        required: false
        schema:
          type: string
          format: date-time
      - name: cursor
        in: query
        description: The pagination cursor value.
        required: false
        schema:
          type: string
      - name: employee_id
        in: query
        description: If provided, will only return timesheet entries for this employee.
        required: false
        schema:
          type: string
      - name: ended_after
        in: query
        description: If provided, will only return timesheet entries ended after this datetime.
        required: false
        schema:
          type: string
          format: date-time
      - name: ended_before
        in: query
        description: If provided, will only return timesheet entries ended before this datetime.
        required: false
        schema:
          type: string
          format: date-time
      - name: expand
        in: query
        description: Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
        required: false
        schema:
          type: array
          items:
            $ref: '#/components/schemas/TimesheetEntriesGetParametersExpandSchemaItems'
      - name: include_deleted_data
        in: query
        description: Indicates whether or not this object has been deleted in the third party platform. Full coverage deletion detection is a premium add-on. Native deletion detection is offered for free with limited coverage. [Learn more](https://docs.merge.dev/integrations/hris/supported-features/).
        required: false
        schema:
          type: boolean
      - name: include_remote_data
        in: query
        description: Whether to include the original data Merge fetched from the third-party to produce these models.
        required: false
        schema:
          type: boolean
      - name: include_shell_data
        in: query
        description: Whether to include shell records. Shell records are empty records (they may contain some metadata but all other fields are null).
        required: false
        schema:
          type: boolean
      - name: modified_after
        in: query
        description: If provided, only objects synced by Merge after this date time will be returned.
        required: false
        schema:
          type: string
          format: date-time
      - name: modified_before
        in: query
        description: If provided, only objects synced by Merge before this date time will be returned.
        required: false
        schema:
          type: string
          format: date-time
      - name: order_by
        in: query
        description: 'Overrides the default ordering for this endpoint. Possible values include: start_time, -start_time.'
        required: false
        schema:
          $ref: '#/components/schemas/TimesheetEntriesGetParametersOrderBy'
      - name: page_size
        in: query
        description: Number of results to return per page. The maximum limit is 100.
        required: false
        schema:
          type: integer
      - name: remote_id
        in: query
        description: The API provider's ID for the given object.
        required: false
        schema:
          type: string
      - name: started_after
        in: query
        description: If provided, will only return timesheet entries started after this datetime.
        required: false
        schema:
          type: string
          format: date-time
      - name: started_before
        in: query
        description: If provided, will only return timesheet entries started before this datetime.
        required: false
        schema:
          type: string
          format: date-time
      - name: Authorization
        in: header
        description: Token-based authentication with required prefix "Bearer"
        required: true
        schema:
          type: string
      - name: X-Account-Token
        in: header
        description: Token identifying the end user.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedTimesheetEntryList'
    post:
      operationId: create
      summary: Create
      description: Creates a `TimesheetEntry` object with the given values.{/* BEGIN_HRIS_TIMESHEETENTRY_CREATE_SUPPORTED_FIELDS */}{/* END_HRIS_TIMESHEETENTRY_CREATE_SUPPORTED_FIELDS */}
      tags:
      - subpackage_timesheetEntries
      parameters:
      - name: is_debug_mode
        in: query
        description: Whether to include debug fields (such as log file links) in the response.
        required: false
        schema:
          type: boolean
      - name: run_async
        in: query
        description: Whether or not third-party updates should be run asynchronously.
        required: false
        schema:
          type: boolean
      - name: Authorization
        in: header
        description: Token-based authentication with required prefix "Bearer"
        required: true
        schema:
          type: string
      - name: X-Account-Token
        in: header
        description: Token identifying the end user.
        required: true
        schema:
          type: string
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimesheetEntryResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimesheetEntryEndpointRequest'
  /hris/v1/timesheet-entries/{id}:
    get:
      operationId: retrieve
      summary: Retrieve
      description: Returns a `TimesheetEntry` object with the given `id`.{/* BEGIN_HRIS_TIMESHEETENTRY_FETCH_SUPPORTED_FIELDS */}{/* END_HRIS_TIMESHEETENTRY_FETCH_SUPPORTED_FIELDS */}
      tags:
      - subpackage_timesheetEntries
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: expand
        in: query
        description: Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
        required: false
        schema:
          type: array
          items:
            $ref: '#/components/schemas/TimesheetEntriesIdGetParametersExpandSchemaItems'
      - name: include_remote_data
        in: query
        description: Whether to include the original data Merge fetched from the third-party to produce these models.
        required: false
        schema:
          type: boolean
      - name: include_shell_data
        in: query
        description: Whether to include shell records. Shell records are empty records (they may contain some metadata but all other fields are null).
        required: false
        schema:
          type: boolean
      - name: Authorization
        in: header
        description: Token-based authentication with required prefix "Bearer"
        required: true
        schema:
          type: string
      - name: X-Account-Token
        in: header
        description: Token identifying the end user.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimesheetEntry'
  /hris/v1/timesheet-entries/meta/post:
    get:
      operationId: meta-post-retrieve
      summary: Meta Post Retrieve
      description: Returns metadata for `TimesheetEntry` POSTs.{/* BEGIN_HRIS_TIMESHEETENTRY_FETCH_SUPPORTED_FIELDS */}{/* END_HRIS_TIMESHEETENTRY_FETCH_SUPPORTED_FIELDS */}
      tags:
      - subpackage_timesheetEntries
      parameters:
      - name: Authorization
        in: header
        description: Token-based authentication with required prefix "Bearer"
        required: true
        schema:
          type: string
      - name: X-Account-Token
        in: header
        description: Token identifying the end user.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetaResponse'
components:
  schemas:
    TimesheetEntryResponse:
      type: object
      properties:
        model:
          $ref: '#/components/schemas/TimesheetEntry'
        warnings:
          type: array
          items:
            $ref: '#/components/schemas/WarningValidationProblem'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorValidationProblem'
        logs:
          type: array
          items:
            $ref: '#/components/schemas/DebugModeLog'
      required:
      - model
      - warnings
      - errors
      title: TimesheetEntryResponse
    DebugModelLogSummary:
      type: object
      properties:
        url:
          type: string
        method:
          type: string
        status_code:
          type: integer
      required:
      - url
      - method
      - status_code
      title: DebugModelLogSummary
    LinkedAccountStatus:
      type: object
      properties:
        linked_account_status:
          type: string
        can_make_request:
          type: boolean
      required:
      - linked_account_status
      - can_make_request
      title: LinkedAccountStatus
    TimesheetEntryFieldMappings:
      type: object
      properties:
        organization_defined_targets:
          type: object
          additionalProperties:
            description: Any type
        linked_account_defined_targets:
          type: object
          additionalProperties:
            description: Any type
      title: TimesheetEntryFieldMappings
    ValidationProblemSource:
      type: object
      properties:
        pointer:
          type: string
      required:
      - pointer
      title: ValidationProblemSource
    ErrorValidationProblem:
      type: object
      properties:
        source:
          $ref: '#/components/schemas/ValidationProblemSource'
        title:
          type: string
        detail:
          type: string
        problem_type:
          type: string
        block_merge_link:
          type: boolean
        raw_error:
          type: string
        error_code:
          type: integer
      required:
      - title
      - detail
      - problem_type
      title: ErrorValidationProblem
    TimesheetEntriesIdGetParametersExpandSchemaItems:
      type: string
      enum:
      - employee
      title: TimesheetEntriesIdGetParametersExpandSchemaItems
    WarningValidationProblem:
      type: object
      properties:
        source:
          $ref: '#/components/schemas/ValidationProblemSource'
        title:
          type: string
        detail:
          type: string
        problem_type:
          type: string
        block_merge_link:
          type: boolean
        raw_error:
          type: string
        error_code:
          type: integer
      required:
      - title
      - detail
      - problem_type
      title: WarningValidationProblem
    TimesheetEntriesGetParametersOrderBy:
      type: string
      enum:
      - -start_time
      - start_time
      title: TimesheetEntriesGetParametersOrderBy
    PaginatedTimesheetEntryList:
      type: object
      properties:
        next:
          type:
          - string
          - 'null'
        previous:
          type:
          - string
          - 'null'
        results:
          type: array
          items:
            $ref: '#/components/schemas/TimesheetEntry'
      title: PaginatedTimesheetEntryList
    TimesheetEntriesGetParametersExpandSchemaItems:
      type: string
      enum:
      - employee
      title: TimesheetEntriesGetParametersExpandSchemaItems
    TimesheetEntryRequest:
      type: object
      properties:
        employee:
          type:
          - string
          - 'null'
          format: uuid
          description: The employee the timesheet entry is for.
        hours_worked:
          type:
          - number
          - 'null'
          format: double
          description: The number of hours logged by the employee.
        start_time:
          type:
          - string
          - 'null'
          format: date-time
          description: The time at which the employee started work.
        end_time:
          type:
          - string
          - 'null'
          format: date-time
          description: The time at which the employee ended work.
        integration_params:
          type:
          - object
          - 'null'
          additionalProperties:
            description: Any type
        linked_account_params:
          type:
          - object
          - 'null'
          additionalProperties:
            description: Any type
      description: '# The Timesheet Entry Object

        ### Description

        The `Timesheet Entry` object is used to track coverage for hours worked by an ''Employee''.



        ### Usage Example

        GET and POST Timesheet Entries'
      title: TimesheetEntryRequest
    TimesheetEntryEndpointRequest:
      type: object
      properties:
        model:
          $ref: '#/components/schemas/TimesheetEntryRequest'
      required:
      - model
      title: TimesheetEntryEndpointRequest
    DebugModeLog:
      type: object
      properties:
        log_id:
          type: string
        dashboard_view:
          type: string
        log_summary:
          $ref: '#/components/schemas/DebugModelLogSummary'
      required:
      - log_id
      - dashboard_view
      - log_summary
      title: DebugModeLog
    RemoteData:
      type: object
      properties:
        path:
          type: string
          description: The third-party API path that is being called.
        data:
          description: The data returned from the third-party for this object in its original, unnormalized format.
      required:
      - path
      description: '# The RemoteData Object

        ### Description

        The `RemoteData` object is used to represent the full data pulled from the third-party API for an object.


        ### Usage Example

        TODO'
      title: RemoteData
    MetaResponse:
      type: object
      properties:
        request_schema:
          type: object
          additionalProperties:
            description: Any type
        status:
          $ref: '#/components/schemas/LinkedAccountStatus'
        has_conditional_params:
          type: boolean
        has_required_linked_account_params:
          type: boolean
        remote_fields:
          type: array
          items:
            type: string
            format: uuid
          description: Remote field values to populate
      required:
      - request_schema
      - has_conditional_params
      - has_required_linked_account_params
      title: MetaResponse
    TimesheetEntry:
      type: object
      properties:
        id:
          type: string
          format: uuid
        remote_id:
          type:
          - string
          - 'null'
          description: The third-party API ID of the matching object.
        created_at:
          type: string
          format: date-time
          description: The datetime that this object was created by Merge.
        modified_at:
          type: string
          format: date-time
          description: The datetime that this object was modified by Merge.
        employee:
          type:
          - string
          - 'null'
          format: uuid
          description: The employee the timesheet entry is for.
        hours_worked:
          type:
          - number
          - 'null'
          format: double
          description: The number of hours logged by the employee.
        start_time:
          type:
          - string
          - 'null'
          format: date-time
          description: The time at which the employee started work.
        end_time:
          type:
          - string
          - 'null'
          format: date-time
          description: The time at which the employee ended work.
        remote_was_deleted:
          type: boolean
          description: Indicates whether or not this object has been deleted in the third party platform. Full coverage deletion detection is a premium add-on. Native deletion detection is offered for free with limited coverage. [Learn more](https://docs.merge.dev/integrations/hris/supported-features/).
        field_mappings:
          oneOf:
          - $ref: '#/components/schemas/TimesheetEntryFieldMappings'
          - type: 'null'
        remote_data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/RemoteData'
      description: '# The Timesheet Entry Object

        ### Description

        The `Timesheet Entry` object is used to track coverage for hours worked by an ''Employee''.



        ### Usage Example

        GET and POST Timesheet Entries'
      title: TimesheetEntry
  securitySchemes:
    tokenAuth:
      type: http
      scheme: bearer
      description: Token-based authentication with required prefix "Bearer"
